server:
  port: 8761
spring:
  application:
    name: eureka-serve
eureka:
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://192.168.43.176:${server.port}
      fetchRegistry: false